name = "Goa"
license = "MIT"
licenselink = "https://github.com/shenoydotme/hugo-goa/blob/master/LICENSE"
description = "Simple Minimalist Hugo Theme"
homepage = "https://github.com/shenoydotme/hugo-goa"
demosite = "https://shenoydotme.github.io/hugo-goa-demo/"
tags = [
  "Roboto",
  "Lato",
  "Roboto Slab",
  "bootstrap",
  "font awesome",
  "minimal",
  "clean",
]
features = [
  "blog",
  "pages",
  "minimal",
  "responsive",
  "404",
  "icons",
  "disqus",
  "analytics",
]

min_version = "v0.154.3"

# If the theme has multiple authors
authors = [
  {name = "Rajesh Shenoy", homepage = "https://shenoy.me"},
  {name = "Papyrus Apps", homepage = "https://papyrusapps.com"},
]
