## Basic Configuration

baseurl = "https://papyrusapps.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Papyrus Apps"
title = "Papyrus Apps"

theme = "hugo-goa"

## Hugo Built-in Features
# Enable if you want to use Disqus
#[services]
#  [services.disqus]
#    shortname = 'your-disqus-shortname'
# Enable if you want to use Google Analytics
#  [services.googleAnalytics]
#    id = 'G-MEASUREMENT_ID'

## Site Settings
[params]
author = "Papyrus Apps"
intro = "Calm, useful software built with care"
description = "Building thoughtful apps at [Papyrus Apps](https://papyrusapps.com)."
authorimage = "headshot.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "<username>"
instagram = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
googlescholar = "<account_id>"
orcid = "0123-4567-8901-2345"
stackoverflow = "<username>"
lastfm = "<username>"
goodreads = "<username>"
gitlab = "<username>"
bitbucket = "<username>"
fivehundredpx = "<username>"
flickr = "<username>"
foursquare = "<username>"
hackernews = "<username>"
kickstarter = "<username>"
patreon = "<username>"
pintrest = "<username>"
steam = "<username>"
reddit = "<username>"
snapchat = "<username>"
youtube = "<channelid>"
keybase = "<username>"
twitch = "<username>"
soundcloud = "<username>"
tumblr = "<username>"
strava = "<username>"
skype = "<username>"
telegram = "<username>"
whatsapp = "<username>"
buymeacoffee = "<username>"
kaggle = "<username>"
holopin = "<username>"
bluesky = "<username>"
email = "you@example.com"
pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "Â© 2026. Papyrus Apps. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
name = "posts"
weight = 100
identifier = "posts"
url = "posts/"
[[menu.main]]
name = "about"
identifier = "about"
weight = 200
url = "about/"
[[menu.main]]
name = "projects"
identifier = "projects"
weight = 300
url = "projects/"
